// Command release builds deterministic release archives for the supported platforms.
package main

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var stableVersion = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+$`)

func main() {
	if len(os.Args) != 3 || !stableVersion.MatchString(os.Args[1]) {
		fmt.Fprintln(os.Stderr, "usage: go run ./tools/release vMAJOR.MINOR.PATCH OUTPUT_DIR")
		os.Exit(1)
	}
	if err := release(os.Args[1], os.Args[2]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func release(version, output string) error {
	if entries, err := os.ReadDir(output); err == nil && len(entries) > 0 {
		return fmt.Errorf("release output directory must be empty")
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(output, 0o755); err != nil {
		return err
	}
	staging, err := os.MkdirTemp("", "skillctrl-release-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(staging)
	var checksums strings.Builder
	var archives []string
	digests := make(map[string]string)
	for _, platform := range [][2]string{{"darwin", "amd64"}, {"darwin", "arm64"}, {"linux", "amd64"}, {"linux", "arm64"}} {
		binary := filepath.Join(staging, "skillctrl")
		build := exec.Command("go", "build", "-trimpath", "-buildvcs=false",
			"-ldflags", "-s -w -X github.com/wwwyo/skillctrl/internal/cli.Version="+version,
			"-o", binary, ".")
		build.Env = platformEnvironment(platform[0], platform[1])
		build.Stdout, build.Stderr = os.Stderr, os.Stderr
		if err := build.Run(); err != nil {
			return fmt.Errorf("build %s/%s: %w", platform[0], platform[1], err)
		}
		name := fmt.Sprintf("skillctrl_%s_%s_%s.tar.gz", strings.TrimPrefix(version, "v"), platform[0], platform[1])
		path := filepath.Join(output, name)
		if err := archive(path, binary); err != nil {
			return err
		}
		file, err := os.Open(path)
		if err != nil {
			return err
		}
		hash := sha256.New()
		_, copyErr := io.Copy(hash, file)
		closeErr := file.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
		digest := hex.EncodeToString(hash.Sum(nil))
		digests[platform[0]+"_"+platform[1]] = digest
		fmt.Fprintf(&checksums, "%s  %s\n", digest, name)
		archives = append(archives, name)
	}
	if err := os.WriteFile(filepath.Join(output, "checksums.txt"), []byte(checksums.String()), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(output, "skillctrl.rb"), []byte(formula(version, digests)), 0o644); err != nil {
		return err
	}
	return json.NewEncoder(os.Stdout).Encode(map[string]any{"version": version, "archives": archives, "checksums": "checksums.txt"})
}

func formula(tag string, digests map[string]string) string {
	version := strings.TrimPrefix(tag, "v")
	var output strings.Builder
	fmt.Fprintf(&output, `# Generated by wwwyo/skillctrl tools/release; edit the generator, not this file.
class Skillctrl < Formula
  desc "Manage agent skills while preserving locally recorded intent"
  homepage "https://github.com/wwwyo/skillctrl"
  version %q
  license "MIT"

`, version)
	for _, osPair := range [][2]string{{"macos", "darwin"}, {"linux", "linux"}} {
		fmt.Fprintf(&output, "  on_%s do\n", osPair[0])
		for _, archPair := range [][2]string{{"arm", "arm64"}, {"intel", "amd64"}} {
			platform := osPair[1] + "_" + archPair[1]
			fmt.Fprintf(&output, "    on_%s do\n", archPair[0])
			fmt.Fprintf(&output, "      url %q\n", "https://github.com/wwwyo/skillctrl/releases/download/"+tag+"/skillctrl_"+version+"_"+platform+".tar.gz")
			fmt.Fprintf(&output, "      sha256 %q\n", digests[platform])
			output.WriteString("    end\n")
		}
		output.WriteString("  end\n\n")
	}
	output.WriteString(`  def install
    bin.install "skillctrl"
  end

  test do
    assert_match "skillctrl version v#{version}", shell_output("#{bin}/skillctrl --version")
    assert_match "prepare", shell_output("#{bin}/skillctrl ci --help")
  end
end
`)
	return output.String()
}

func platformEnvironment(goos, goarch string) []string {
	var environment []string
	for _, entry := range os.Environ() {
		key, _, _ := strings.Cut(entry, "=")
		switch key {
		case "GOOS", "GOARCH", "CGO_ENABLED", "GOAMD64", "GOARM64", "GOFLAGS", "GOWORK", "GOTOOLCHAIN":
			continue
		}
		environment = append(environment, entry)
	}
	// Host-specific tuning would make the advertised baseline binaries unusable
	// on older machines, and inherited GOFLAGS would change published artifacts.
	return append(environment, "GOOS="+goos, "GOARCH="+goarch, "CGO_ENABLED=0", "GOAMD64=v1", "GOARM64=v8.0", "GOFLAGS=", "GOWORK=off", "GOTOOLCHAIN=local")
}

func archive(path, binary string) (err error) {
	output, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { err = firstError(err, output.Close()) }()
	compressed := gzip.NewWriter(output)
	defer func() { err = firstError(err, compressed.Close()) }()
	tape := tar.NewWriter(compressed)
	defer func() { err = firstError(err, tape.Close()) }()
	for _, item := range []struct {
		name, source string
		mode         int64
	}{{"LICENSE", "LICENSE", 0o644}, {"THIRD_PARTY_NOTICES", "THIRD_PARTY_NOTICES", 0o644}, {"skillctrl", binary, 0o755}} {
		file, openErr := os.Open(item.source)
		if openErr != nil {
			return openErr
		}
		info, statErr := file.Stat()
		if statErr != nil {
			file.Close()
			return statErr
		}
		writeErr := tape.WriteHeader(&tar.Header{Name: item.name, Mode: item.mode, Size: info.Size(), ModTime: time.Unix(0, 0), Format: tar.FormatUSTAR})
		if writeErr == nil {
			_, writeErr = io.Copy(tape, file)
		}
		closeErr := file.Close()
		if err := firstError(writeErr, closeErr); err != nil {
			return err
		}
	}
	return nil
}

func firstError(a, b error) error {
	if a != nil {
		return a
	}
	return b
}
